addons:
  apt:
    packages:
    - libglu1-mesa

language: generic

cache:
  directories:
  - blender

env: # build matrix
  global:
    - CC_TEST_REPORTER_ID=6bdf928af38529955b976480e38018d63e64087331ba7ed6eb3c645934677833
  jobs:
    - BLENDER_VERSION=2.77
    - BLENDER_VERSION=2.78
    - BLENDER_VERSION=2.79
    - BLENDER_VERSION=2.80
    - BLENDER_VERSION=2.81
    - BLENDER_VERSION=2.82
    - BLENDER_VERSION=2.83
    - BLENDER_VERSION=2.90
    - BLENDER_VERSION=2.91
    - BLENDER_VERSION=2.92
    - BLENDER_VERSION=2.93

install:
  - bash ./tests/ci-prepare.sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./blender/$BLENDER_VERSION/blender --factory-startup -noaudio -b --python-exit-code 1 --python tests/runner.py

after_success:
  - if [[ "$BLENDER_VERSION" == "2.90" ]; then
  -   ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  -   bash <(curl -s https://codecov.io/bash)
  - fi
